# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cdb9a7e8e52898d25e90188b080270abc8510b15b4bde98ab5385cd660d4e573149a8b01fc98d1c09ada280e77680cf3899437e30c83bb6ede867b306ec7a13

test:
  secret_key_base: 29e4e68036313adaed1ddf7c3183415751708bdd484f60d7238976a1e3df6e56e316ebdb1c888763af58b5e1e658eb2260861aa2f8950a1b3b02dfb9051141c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
